basePath: /
definitions:
  domain.Object:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  types.GetObjectHandlerResponse:
    properties:
      value:
        type: string
    type: object
  types.GetTaskResultHandlerResponse:
    properties:
      result:
        type: string
    type: object
  types.GetTaskStatusHandlerResponse:
    properties:
      status:
        type: string
    type: object
  types.PostTaskHandlerRequest:
    properties:
      data:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /object:
    delete:
      consumes:
      - application/json
      description: Delete an object by its key
      parameters:
      - description: Key of the object
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Object deleted successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Object not found
          schema:
            type: string
      summary: Delete an object
      tags:
      - object
    get:
      consumes:
      - application/json
      description: Get an object by its key
      parameters:
      - description: Key of the object
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetObjectHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Object not found
          schema:
            type: string
      summary: Get an object
      tags:
      - object
    post:
      consumes:
      - application/json
      description: Create a new object with the specified key and value
      parameters:
      - description: Object data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Object'
      produces:
      - application/json
      responses:
        "200":
          description: Object created successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create an object
      tags:
      - object
    put:
      consumes:
      - application/json
      description: Create or update an object with the specified key and value
      parameters:
      - description: Object data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Object'
      produces:
      - application/json
      responses:
        "200":
          description: Object created or updated successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create or update an object
      tags:
      - object
  /task:
    post:
      consumes:
      - application/json
      description: Submit a new task for processing
      parameters:
      - description: Task data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.PostTaskHandlerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Task ID returned successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create a new task with generated task_id
      tags:
      - task
  /task/{task_id}/result:
    get:
      consumes:
      - application/json
      description: Retrieve the result of a completed task by its ID
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Task result received successfully
          schema:
            $ref: '#/definitions/types.GetTaskResultHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task result
      tags:
      - task
  /task/{task_id}/status:
    get:
      consumes:
      - application/json
      description: Retrieve the status of a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Task status received successfully
          schema:
            $ref: '#/definitions/types.GetTaskStatusHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task status
      tags:
      - task
swagger: "2.0"
